"""Acceptance tests for: Issue #587 — pipeline_intent_validator session scoping

Generated by acceptance-first pipeline mode.
Validates that the step ordering check in pipeline_intent_validator.py is
session-scoped and does not produce false CRITICAL findings from cross-session
event comparisons in the same daily log file.
"""

import json
import sys
from pathlib import Path

import pytest

from .conftest import PROJECT_ROOT


@pytest.mark.genai
class TestAcceptanceValidatorSessionScoping:
    """Acceptance criteria from Issue #587."""

    # -------------------------------------------------------------------------
    # AC1: PipelineEvent carries session_id
    # -------------------------------------------------------------------------

    def test_pipeline_event_has_session_id_field(self):
        """PipelineEvent dataclass must have a session_id field."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        # Check the dataclass definition includes session_id
        assert "session_id" in content, (
            "PipelineEvent must include session_id field for session-scoped validation"
        )

    # -------------------------------------------------------------------------
    # AC2: SubagentStop events populated with session_id during parsing
    # -------------------------------------------------------------------------

    def test_subagent_stop_session_id_populated(self):
        """parse_session_logs must populate session_id on SubagentStop events."""
        sys.path.insert(0, str(PROJECT_ROOT / "plugins/autonomous-dev/lib"))
        from pipeline_intent_validator import parse_session_logs
        import tempfile

        # Create a JSONL log with a SubagentStop event that has session_id
        entry = {
            "timestamp": "2026-03-28T10:00:00+00:00",
            "hook": "SubagentStop",
            "session_id": "test-session-abc",
            "subagent_type": "implementer",
        }
        with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as f:
            f.write(json.dumps(entry) + "\n")
            tmp_path = Path(f.name)

        try:
            events = parse_session_logs(tmp_path)
            subagent_events = [e for e in events if e.pipeline_action == "agent_completion"]
            assert len(subagent_events) >= 1, "Should parse at least one SubagentStop event"
            assert subagent_events[0].session_id == "test-session-abc", (
                "SubagentStop event must carry session_id from the JSONL entry"
            )
        finally:
            tmp_path.unlink(missing_ok=True)

    # -------------------------------------------------------------------------
    # AC3: Cross-session events don't produce false ordering findings
    # -------------------------------------------------------------------------

    def test_cross_session_no_false_ordering_findings(self):
        """validate_pipeline_intent on multi-session log must not produce false ordering findings."""
        sys.path.insert(0, str(PROJECT_ROOT / "plugins/autonomous-dev/lib"))
        from pipeline_intent_validator import validate_pipeline_intent
        import tempfile

        # Session A: correct ordering (planner at 10:00, implementer at 10:10)
        # Session B: correct ordering (planner at 09:00, implementer at 09:10)
        # But cross-session: B's implementer (09:10) < A's planner (10:00) — would be false positive
        entries = [
            {"timestamp": "2026-03-28T10:00:00+00:00", "hook": "PostToolUse", "tool": "Agent",
             "session_id": "session-a", "input_summary": "subagent_type: planner"},
            {"timestamp": "2026-03-28T10:10:00+00:00", "hook": "PostToolUse", "tool": "Agent",
             "session_id": "session-a", "input_summary": "subagent_type: implementer"},
            {"timestamp": "2026-03-28T09:00:00+00:00", "hook": "PostToolUse", "tool": "Agent",
             "session_id": "session-b", "input_summary": "subagent_type: planner"},
            {"timestamp": "2026-03-28T09:10:00+00:00", "hook": "PostToolUse", "tool": "Agent",
             "session_id": "session-b", "input_summary": "subagent_type: implementer"},
        ]

        with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as f:
            for entry in entries:
                f.write(json.dumps(entry) + "\n")
            tmp_path = Path(f.name)

        try:
            findings = validate_pipeline_intent(tmp_path)
            ordering_findings = [f for f in findings if f.get("check") == "step_ordering"
                                 or "ordering" in str(f).lower()]
            # No false CRITICAL ordering violations
            critical_ordering = [f for f in ordering_findings
                                 if f.get("severity") == "CRITICAL"]
            assert len(critical_ordering) == 0, (
                f"Cross-session events must not produce false CRITICAL ordering findings. "
                f"Got: {critical_ordering}"
            )
        finally:
            tmp_path.unlink(missing_ok=True)

    # -------------------------------------------------------------------------
    # AC4: Single-session ordering violations still detected
    # -------------------------------------------------------------------------

    def test_single_session_ordering_violation_still_detected(self):
        """A real ordering violation within a single session must still be detected."""
        sys.path.insert(0, str(PROJECT_ROOT / "plugins/autonomous-dev/lib"))
        from pipeline_intent_validator import validate_pipeline_intent
        import tempfile

        # Single session with implementer before planner (violation)
        entries = [
            {"timestamp": "2026-03-28T10:00:00+00:00", "hook": "PostToolUse", "tool": "Agent",
             "session_id": "session-x", "input_summary": "subagent_type: implementer"},
            {"timestamp": "2026-03-28T10:10:00+00:00", "hook": "PostToolUse", "tool": "Agent",
             "session_id": "session-x", "input_summary": "subagent_type: planner"},
        ]

        with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as f:
            for entry in entries:
                f.write(json.dumps(entry) + "\n")
            tmp_path = Path(f.name)

        try:
            findings = validate_pipeline_intent(tmp_path)
            ordering_findings = [f for f in findings if "ordering" in str(f).lower()
                                 or f.get("check") == "step_ordering"]
            # Should detect the real violation
            assert len(ordering_findings) > 0, (
                "Real ordering violation within a single session must still be detected"
            )
        finally:
            tmp_path.unlink(missing_ok=True)

    # -------------------------------------------------------------------------
    # AC5: Backward compatibility — empty session_id events grouped together
    # -------------------------------------------------------------------------

    def test_empty_session_id_backward_compatible(self):
        """Events without session_id should be grouped together and checked."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        # The implementation should handle empty/missing session_id gracefully
        assert 'session_id' in content, (
            "pipeline_intent_validator must reference session_id for grouping logic"
        )
