"""Acceptance tests for: Issues #561 + #562 — Compression prevention + doc verdict false positive fix.

Generated by acceptance-first pipeline mode.
Validates feature intent using LLM-as-judge evaluation.
"""
import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceCompressionPrevention:
    """Acceptance criteria for Issue #561 — progressive compression prevention."""

    def test_finding_has_recommended_action_field(self, genai):
        """Finding dataclass must include a recommended_action field for actionable fixes."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does the Finding dataclass include a recommended_action field?",
            context=context,
            criteria="Finding must have a recommended_action field (Optional[str], default None) that can carry specific instructions like 'Reload prompt from agents/reviewer.md'. Must be backward-compatible (default None so existing callers are unaffected).",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_compression_findings_include_reload_recommendation(self, genai):
        """detect_progressive_compression findings must include a prompt reload recommendation."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="When detect_progressive_compression creates a finding, does it populate recommended_action with a specific prompt reload instruction?",
            context=context,
            criteria="Each compression finding must set recommended_action to a string that tells the coordinator to reload the agent's prompt from disk (referencing the agents/*.md file path). Must not be None or empty.",
            category="behavior",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_get_minimum_prompt_content_exists(self, genai):
        """A function must exist to read minimum prompt content from agent .md files."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does this module contain a function that reads agent prompt content from .md files on disk?",
            context=context,
            criteria="Must have a function (named something like get_minimum_prompt_content) that takes an agent_type string and a directory path, validates the agent_type against a whitelist, reads the corresponding .md file, and returns the first ~200 words as a minimum prompt baseline. Must return None for invalid/missing agent types.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_agent_type_whitelist_validation(self, genai):
        """get_minimum_prompt_content must validate agent_type against a whitelist."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does get_minimum_prompt_content validate the agent_type parameter against a known whitelist before constructing file paths?",
            context=context,
            criteria="The function must check agent_type is in a known set (like STEP_ORDER keys) before constructing any file path. Path traversal attempts like '../../etc/passwd' must be rejected by returning None. This is a security requirement.",
            category="security",
        )
        assert result["band"] != "hard_fail", result["reasoning"]


@pytest.mark.genai
class TestAcceptanceDocVerdictFalsePositiveFix:
    """Acceptance criteria for Issue #562 — doc verdict missing false positive fix."""

    def test_invocation_completion_correlation_exists(self, genai):
        """A helper must exist to correlate agent invocations with completions."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does this module contain a function that pairs agent invocation events with their completion events?",
            context=context,
            criteria="Must have a helper function that matches PostToolUse agent_invocation events with SubagentStop agent_completion events by subagent_type and temporal proximity. Returns pairs of (invocation, completion_or_None). Must handle multiple agents of the same type and unmatched invocations.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_doc_verdict_uses_completion_word_count(self, genai):
        """detect_doc_verdict_missing must read word counts from completion events, not invocations."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does detect_doc_verdict_missing use completion (SubagentStop) events for result_word_count instead of invocation (PostToolUse) events?",
            context=context,
            criteria="The function must NOT read result_word_count from agent_invocation events (which are always 0). Instead it must use the correlated agent_completion event's result_word_count. When no completion event exists, it should flag as missing. When completion has very low word count (e.g., < 30 words), it should flag as insufficient.",
            category="behavior",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_no_false_positive_when_completion_has_output(self, genai):
        """doc-master invocations with healthy completion output must NOT produce findings."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="If a doc-master invocation event has result_word_count=0 but its matched completion event has result_word_count=200, does detect_doc_verdict_missing correctly produce NO finding?",
            context=context,
            criteria="The function must not flag doc-master as missing when the invocation shows 0 words but the correlated completion shows adequate output (>= threshold). The false positive from reading invocation word counts must be eliminated.",
            category="behavior",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
