"""Acceptance tests for: Issue #444 — Refactor /implement from inline to thin coordinator

Generated by acceptance-first pipeline mode.
Validates that implement.md is a thin coordinator that delegates to agents
while preserving all HARD GATEs and pipeline enforcement.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceImplementThinCoordinator:
    """Acceptance criteria from planner output for Issue #444."""

    def test_coordinator_is_thin(self, genai):
        """implement.md should be ~100 lines, not 383+"""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        line_count = len(content.strip().split("\n"))
        result = genai.judge(
            question=f"This command file is {line_count} lines. Is it a thin coordinator (<150 lines) that delegates to agents, or a monolithic inline prompt (>200 lines) that contains all pipeline logic?",
            context=content,
            criteria="A thin coordinator should: parse args, check alignment, invoke agents via Agent/Task tool, run HARD GATE checks inline, and report results. It should NOT contain detailed agent instructions, verbose code templates, or multi-paragraph step descriptions.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_all_hard_gates_preserved(self, genai):
        """All HARD GATEs must survive the refactor"""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does this command preserve ALL required HARD GATEs for pipeline enforcement?",
            context=content,
            criteria="Required HARD GATEs: (1) STEP 5 test gate — pytest must pass with 0 failures before proceeding, (2) STEP 5 no-new-skips — @pytest.mark.skip forbidden, (3) STEP 5.5 hook registration — new hooks must be registered, (4) STEP 8.5 documentation congruence — congruence tests must pass, (5) STEP 9 mandatory — continuous-improvement-analyst must be launched. All must use FORBIDDEN/REQUIRED enforcement language.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_agents_delegated_not_inline(self, genai):
        """Agent work should be delegated via Agent/Task tool, not described inline"""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does this command delegate specialist work to agents via Agent/Task tool calls, rather than containing inline instructions for what each agent should do?",
            context=content,
            criteria="The coordinator should invoke agents by name (researcher-local, researcher, planner, implementer, reviewer, security-auditor, doc-master, continuous-improvement-analyst) using Agent or Task tool syntax. It should NOT contain detailed instructions about what each agent should search for, how to write plans, or how to review code — those belong in agents/*.md files.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_context_handoff_between_stages(self, genai):
        """Coordinator must pass context between agents explicitly"""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does the coordinator explicitly describe what context to pass from one stage to the next?",
            context=content,
            criteria="Since agents run in isolated context, the coordinator must: (1) pass merged research output to planner, (2) pass planner output to implementer, (3) pass implementation summary to reviewer/security-auditor/doc-master, (4) pass feature description to all agents. Each Agent tool call should include the relevant outputs from prior stages.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_all_modes_preserved(self, genai):
        """All routing modes must still work: full, tdd-first, batch, issues, resume"""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does this command preserve all routing modes?",
            context=content,
            criteria="Must support: (1) default full pipeline (acceptance-first), (2) --tdd-first mode, (3) --batch mode routing to implement-batch.md, (4) --issues mode routing to implement-batch.md, (5) --resume mode routing to implement-resume.md. Auto-detect batch issues mode for 2+ issue references.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_coordinator_forbidden_list_preserved(self, genai):
        """The COORDINATOR FORBIDDEN LIST must survive the refactor"""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does this command include a COORDINATOR FORBIDDEN LIST that prevents pipeline violations?",
            context=content,
            criteria="Must include explicit forbidden behaviors: skipping steps, summarizing agent output instead of passing full results, declaring 'good enough' on failing tests, running validation before test gate passes, combining sequential steps, treating STEP 8 as final, cleaning up before STEP 9.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
