"""Acceptance tests for: Issue #585 — Strengthen alignment gate: hook-level enforcement + scope injection into sub-agents

Generated by acceptance-first pipeline mode.
Validates that the alignment gate is enforced at hook level (unified_pre_tool.py),
that pipeline state tracks alignment_passed, that HMAC covers the new field,
and that implement.md injects PROJECT.md GOALS/SCOPE into planner and reviewer.
"""

import json
import sys
from pathlib import Path

import pytest

from .conftest import PROJECT_ROOT


@pytest.mark.genai
class TestAcceptanceAlignmentGate:
    """Acceptance criteria from Issue #585."""

    # -------------------------------------------------------------------------
    # AC1: Pipeline state schema supports alignment_passed
    # -------------------------------------------------------------------------

    def test_pipeline_state_schema_supports_alignment_passed(self):
        """pipeline_state.py _compute_state_hmac must include alignment_passed field."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_state.py").read_text()
        assert "alignment_passed" in content, (
            "_compute_state_hmac must reference 'alignment_passed' to include it in "
            "the HMAC-protected critical fields. Field not found in pipeline_state.py."
        )

    def test_compute_state_hmac_includes_alignment_passed(self):
        """_compute_state_hmac must include alignment_passed in its message parts."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_state.py").read_text()
        func_start = content.find("def _compute_state_hmac(")
        assert func_start != -1, "_compute_state_hmac function must exist in pipeline_state.py"
        # Extract the function body (generous window — function is ~30 lines)
        func_body = content[func_start : func_start + 1500]
        assert "alignment_passed" in func_body, (
            "_compute_state_hmac function body must reference 'alignment_passed' "
            "to include it in the signed HMAC message parts. "
            "Without this, alignment_passed can be tampered without detection."
        )

    # -------------------------------------------------------------------------
    # AC2: Hook enforcement — _has_alignment_passed function exists
    # -------------------------------------------------------------------------

    def test_hook_has_alignment_passed_function(self, genai):
        """unified_pre_tool.py must have a function that checks alignment_passed in state."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question=(
                "Does this hook contain a function (named _has_alignment_passed or similar) "
                "that reads the pipeline state file and returns whether alignment has passed?"
            ),
            context=content,
            criteria=(
                "There must be a function (e.g., _has_alignment_passed, _check_alignment_gate, or similar) "
                "that reads /tmp/implement_pipeline_state.json (or the pipeline state file), "
                "checks for an 'alignment_passed' field set to true, and returns a bool. "
                "The function must exist — a comment or reference alone is insufficient."
            ),
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    # -------------------------------------------------------------------------
    # AC3: Hook blocks Write/Edit to code files when alignment_passed is False
    # -------------------------------------------------------------------------

    def test_hook_blocks_code_write_when_alignment_not_passed(self, genai):
        """When explicit implement is active and alignment_passed is False, Write/Edit to code files must be blocked."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question=(
                "When /implement is explicitly invoked (explicitly_invoked=true in state file) "
                "AND alignment_passed is False (or absent), does the hook deny Write/Edit to code files?"
            ),
            context=content,
            criteria=(
                "The hook must deny Write/Edit to source code files (e.g., .py, .ts, .js) "
                "when the pipeline state file has explicitly_invoked=true but alignment_passed is False or missing. "
                "This must be a 'deny' decision, not just a warning. "
                "The check must fire before the pipeline agent bypass to prevent skipping alignment."
            ),
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    # -------------------------------------------------------------------------
    # AC4: Hook allows Write/Edit when alignment_passed is True
    # -------------------------------------------------------------------------

    def test_hook_allows_code_write_when_alignment_passed(self, genai):
        """When alignment_passed is True, Write/Edit to code files is allowed (subject to existing checks)."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question=(
                "When the pipeline state file has both explicitly_invoked=true AND alignment_passed=true, "
                "is Write/Edit to code files allowed to proceed (not blocked by the alignment gate)?"
            ),
            context=content,
            criteria=(
                "The alignment gate must NOT block Write/Edit when alignment_passed=true. "
                "The check must be conditional: block only when alignment has NOT passed. "
                "When alignment_passed=true, the tool call must proceed to the normal pipeline agent checks."
            ),
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    # -------------------------------------------------------------------------
    # AC5: Scope injection to planner in STEP 5
    # -------------------------------------------------------------------------

    def test_step5_passes_project_goals_and_scope_to_planner(self, genai):
        """implement.md STEP 5 must instruct coordinator to pass PROJECT.md GOALS and SCOPE to planner."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        step5_start = content.find("### STEP 5:")
        assert step5_start != -1, "STEP 5 section not found in implement.md"
        step6_start = content.find("### STEP 6:", step5_start)
        step5_text = (
            content[step5_start:step6_start]
            if step6_start != -1
            else content[step5_start : step5_start + 2000]
        )
        result = genai.judge(
            question="Does STEP 5 instruct the coordinator to pass PROJECT.md GOALS and SCOPE to the planner agent?",
            context=step5_text,
            criteria=(
                "STEP 5 must explicitly instruct the coordinator to read PROJECT.md and pass "
                "the GOALS section and/or SCOPE section to the planner agent. "
                "A vague 'pass context' instruction is insufficient — it must specifically mention "
                "PROJECT.md GOALS and SCOPE (or equivalent wording like 'project goals', 'in-scope', 'out-of-scope'). "
                "This ensures the planner operates within validated project scope."
            ),
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    # -------------------------------------------------------------------------
    # AC6: Scope injection to reviewer in STEP 10a
    # -------------------------------------------------------------------------

    def test_step10a_passes_project_scope_to_reviewer(self, genai):
        """implement.md STEP 10a must instruct coordinator to pass PROJECT.md SCOPE to reviewer."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        step10a_start = content.find("STEP 10a:")
        assert step10a_start != -1, "STEP 10a section not found in implement.md"
        step10b_start = content.find("STEP 10b:", step10a_start)
        step10a_text = (
            content[step10a_start:step10b_start]
            if step10b_start != -1
            else content[step10a_start : step10a_start + 2000]
        )
        result = genai.judge(
            question="Does STEP 10a instruct the coordinator to pass PROJECT.md SCOPE to the reviewer agent?",
            context=step10a_text,
            criteria=(
                "STEP 10a must explicitly instruct the coordinator to pass PROJECT.md SCOPE "
                "(or GOALS+SCOPE) to the reviewer agent. "
                "The reviewer needs scope context to identify out-of-scope changes. "
                "A generic 'pass context' instruction is insufficient — it must reference "
                "PROJECT.md scope/goals by name."
            ),
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    # -------------------------------------------------------------------------
    # AC7: STEP 2 writes alignment_passed: true to state file
    # -------------------------------------------------------------------------

    def test_step2_writes_alignment_passed_to_state_file(self, genai):
        """implement.md STEP 2 must include code that writes alignment_passed: true to the state file."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        step2_start = content.find("### STEP 2:")
        assert step2_start != -1, "STEP 2 section not found in implement.md"
        step3_start = content.find("### STEP 3:", step2_start)
        step2_text = (
            content[step2_start:step3_start]
            if step3_start != -1
            else content[step2_start : step2_start + 2000]
        )
        result = genai.judge(
            question=(
                "Does STEP 2 include a code block or instruction that writes 'alignment_passed: true' "
                "to the pipeline state file (/tmp/implement_pipeline_state.json)?"
            ),
            context=step2_text,
            criteria=(
                "After a successful alignment check in STEP 2, there must be a code block "
                "(Python or bash) that writes 'alignment_passed': true to /tmp/implement_pipeline_state.json "
                "(or equivalent pipeline state path). "
                "This flag must be written ONLY on alignment success, not unconditionally. "
                "The hook reads this flag to enforce the alignment gate."
            ),
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    # -------------------------------------------------------------------------
    # AC8: Read tools not affected by alignment gate
    # -------------------------------------------------------------------------

    def test_read_tools_not_blocked_by_alignment_gate(self, genai):
        """Alignment gate must not block Read, Grep, Glob tools regardless of alignment state."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question=(
                "Does the alignment gate check specifically exclude Read, Grep, and Glob tools "
                "from being blocked?"
            ),
            context=content,
            criteria=(
                "The alignment gate enforcement (block when alignment_passed is False) "
                "must NOT apply to read-only tools: Read, Grep, Glob, WebSearch, WebFetch. "
                "These tools do not write code and must never be blocked by the alignment gate. "
                "The gate must check the tool name and only block write operations (Write, Edit)."
            ),
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    # -------------------------------------------------------------------------
    # AC9: Non-code files (docs/config) not blocked by alignment gate
    # -------------------------------------------------------------------------

    def test_non_code_files_not_blocked_by_alignment_gate(self, genai):
        """Alignment gate must not block Write to docs or config files."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question=(
                "Does the alignment gate correctly exclude non-code files "
                "(docs/*.md, *.json, *.yaml, *.toml) from being blocked?"
            ),
            context=content,
            criteria=(
                "The alignment gate must only block Write/Edit to source code files. "
                "Non-code files — documentation (*.md), configuration (*.json, *.yaml, *.toml), "
                "and test data files — must NOT be blocked by the alignment gate. "
                "The gate must target code file extensions or known code directories, not all file writes."
            ),
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    # -------------------------------------------------------------------------
    # AC10: HMAC tampering detected — modifying alignment_passed without re-signing fails
    # -------------------------------------------------------------------------

    def test_hmac_tampering_detected_on_alignment_passed_change(self):
        """Modifying alignment_passed without re-signing the HMAC must fail verification."""
        sys.path.insert(0, str(PROJECT_ROOT / "plugins/autonomous-dev/lib"))
        try:
            from pipeline_state import sign_state, verify_state_hmac
        except ImportError as exc:
            pytest.skip(f"pipeline_state module not importable: {exc}")

        # Create a signed state with alignment_passed=False
        state: dict = {
            "session_start": "2026-01-01T00:00:00",
            "mode": "full",
            "run_id": "test-alignment-gate-tampering",
            "explicitly_invoked": True,
            "alignment_passed": False,
        }
        session_id = "test-session-id"
        signed_state = sign_state(state.copy(), session_id)

        # Verify original signature passes
        assert verify_state_hmac(signed_state, session_id), (
            "Freshly signed state must verify successfully before tampering."
        )

        # Tamper: flip alignment_passed to True without re-signing
        tampered_state = dict(signed_state)
        tampered_state["alignment_passed"] = True

        # Verification must fail after tampering
        assert not verify_state_hmac(tampered_state, session_id), (
            "Tampered state (alignment_passed changed without re-signing) must fail HMAC verification. "
            "If _compute_state_hmac does not include alignment_passed in its message, "
            "this tampering goes undetected — a critical security gap."
        )
