"""Acceptance tests for: /refactor command — unified code, docs, and test optimization

Generated by acceptance-first pipeline mode.
Validates that the /refactor command provides shape analysis, waste detection,
doc redundancy detection, dead code detection, and backward-compatible /sweep alias.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceRefactorCommand:
    """Acceptance criteria for /refactor command (Issue #507)."""

    def test_refactor_command_exists(self):
        """The /refactor command must exist as a valid command file."""
        cmd_path = PROJECT_ROOT / "plugins/autonomous-dev/commands/refactor.md"
        assert cmd_path.exists(), f"Missing command: {cmd_path}"

    def test_refactor_command_has_correct_frontmatter(self):
        """The /refactor command must have proper YAML frontmatter."""
        import yaml

        cmd_path = PROJECT_ROOT / "plugins/autonomous-dev/commands/refactor.md"
        content = cmd_path.read_text()
        # Extract frontmatter
        parts = content.split("---", 2)
        assert len(parts) >= 3, "Command must have YAML frontmatter"
        fm = yaml.safe_load(parts[1])
        assert fm.get("name") == "refactor"
        assert fm.get("user-invocable") is True

    def test_refactor_analyzer_library_exists(self):
        """The refactor_analyzer.py library must exist."""
        lib_path = PROJECT_ROOT / "plugins/autonomous-dev/lib/refactor_analyzer.py"
        assert lib_path.exists(), f"Missing library: {lib_path}"

    def test_refactor_analyzer_has_required_classes(self):
        """RefactorAnalyzer must export required classes."""
        import ast

        lib_path = PROJECT_ROOT / "plugins/autonomous-dev/lib/refactor_analyzer.py"
        tree = ast.parse(lib_path.read_text())
        class_names = [node.name for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]
        assert "RefactorAnalyzer" in class_names
        assert "RefactorFinding" in class_names
        assert "RefactorReport" in class_names

    def test_refactor_analyzer_has_test_shape_analysis(self):
        """RefactorAnalyzer must have test shape analysis method."""
        import ast

        lib_path = PROJECT_ROOT / "plugins/autonomous-dev/lib/refactor_analyzer.py"
        tree = ast.parse(lib_path.read_text())
        methods = []
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == "RefactorAnalyzer":
                methods = [n.name for n in node.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
        assert "analyze_tests" in methods, "RefactorAnalyzer must have analyze_tests method"

    def test_refactor_analyzer_has_doc_redundancy_analysis(self):
        """RefactorAnalyzer must have doc redundancy analysis method."""
        import ast

        lib_path = PROJECT_ROOT / "plugins/autonomous-dev/lib/refactor_analyzer.py"
        tree = ast.parse(lib_path.read_text())
        methods = []
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == "RefactorAnalyzer":
                methods = [n.name for n in node.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
        assert "analyze_docs" in methods, "RefactorAnalyzer must have analyze_docs method"

    def test_refactor_analyzer_has_dead_code_analysis(self):
        """RefactorAnalyzer must have dead code analysis method."""
        import ast

        lib_path = PROJECT_ROOT / "plugins/autonomous-dev/lib/refactor_analyzer.py"
        tree = ast.parse(lib_path.read_text())
        methods = []
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == "RefactorAnalyzer":
                methods = [n.name for n in node.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
        assert "analyze_code" in methods, "RefactorAnalyzer must have analyze_code method"

    def test_refactor_analyzer_composes_sweep_analyzer(self, genai):
        """RefactorAnalyzer must compose SweepAnalyzer for --quick mode, not duplicate it."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/lib/refactor_analyzer.py").read_text()
        result = genai.judge(
            question="Does this module import and compose SweepAnalyzer (from sweep_analyzer) for its quick/sweep mode, rather than reimplementing sweep functionality?",
            context=content,
            criteria="The module must import SweepAnalyzer and delegate quick sweep operations to it. It must NOT reimplement SweepAnalyzer's detection logic (dead tests, doc drift, orphan files). Composition via instantiation and delegation is required.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_sweep_command_is_alias(self, genai):
        """The /sweep command must redirect to /refactor --quick."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/sweep.md").read_text()
        result = genai.judge(
            question="Does this command act as an alias that redirects to /refactor --quick?",
            context=content,
            criteria="The command must clearly indicate it is an alias for /refactor --quick. It should either directly redirect or invoke /refactor with the --quick flag. It must NOT contain its own independent analysis logic.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_refactor_command_supports_all_modes(self, genai):
        """The /refactor command must support --tests, --docs, --code, --fix, --quick flags."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/refactor.md").read_text()
        result = genai.judge(
            question="Does this command parse and handle all five flags: --tests, --docs, --code, --fix, and --quick?",
            context=content,
            criteria="The command must have argument parsing that recognizes --tests, --docs, --code, --fix, and --quick. Each flag must route to distinct behavior. --fix must be combinable with the mode flags. Running with no mode flags must default to all three modes (tests + docs + code).",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
