"""Acceptance tests for: Pipeline Verbosity — detailed progress output from /implement

Generated by acceptance-first pipeline mode.
Validates that implement.md, implement-fix.md, and implement-batch.md
instruct the coordinator to output structured progress banners, agent
completion lines, gate results, and a final summary with timing.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptancePipelineVerbosity:
    """Acceptance criteria for pipeline verbosity feature."""

    def test_protocol_section_exists(self, genai):
        """implement.md must contain a Pipeline Progress Protocol section."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does this command file contain a dedicated 'Pipeline Progress Protocol' section that defines output formats for step banners, agent completion, gate results, and timing?",
            context=content,
            criteria="The protocol section should: (1) define a step banner format with step number, total steps, step name, and agent model(s), (2) define agent completion line format with elapsed time, (3) define HARD GATE result format (PASS/BLOCKED), (4) define test gate result format with pass/fail/skip counts, (5) define time formatting rules (Xs for <60s, M:SS for 60s+), (6) define a final summary table format. It should be a single cohesive section, not scattered across steps.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_step_banners_referenced(self, genai):
        """Each pipeline step must reference the progress protocol."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does each pipeline step (STEP 0.5 through STEP 9) include an instruction for the coordinator to output a progress banner and/or capture timing?",
            context=content,
            criteria="Each step should have a brief instruction (1-2 lines) telling the coordinator to output a step banner per the Pipeline Progress Protocol and capture the step start time. This can be a short reference like 'Output step banner per Protocol' rather than repeating the full format at every step.",
            category="completeness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_timing_capture_instructions(self, genai):
        """Timing capture must be specified for elapsed time calculation."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does this command file include instructions for the coordinator to capture timestamps and calculate elapsed time per step and for the total pipeline?",
            context=content,
            criteria="The protocol should specify: (1) a pipeline start timestamp captured at STEP 0, (2) per-step start/end time capture (e.g., via `date +%s`), (3) elapsed time calculation, (4) time formatting rules. The final summary must include per-step elapsed time and total pipeline time.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_final_summary_table(self, genai):
        """STEP 8 must define a structured summary table with timing."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does STEP 8 (Report and Finalize) define a structured summary table that lists all steps with their agent(s), elapsed time, and status, plus total pipeline time?",
            context=content,
            criteria="STEP 8 should output a table or structured format showing: each step number, agent name(s), elapsed time, and result status (done/PASS/FAIL). It should also show total pipeline elapsed time, files changed count, test pass/fail counts, and security PASS/FAIL. This replaces or extends the current one-liner 'Report: 1-line per agent'.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_fix_mode_has_progress(self, genai):
        """implement-fix.md must include progress output instructions."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement-fix.md").read_text()
        result = genai.judge(
            question="Does this fix-mode command file include progress output instructions adapted for its shorter pipeline (3-4 steps)?",
            context=content,
            criteria="Fix mode should: (1) define or reference a progress protocol with step banners (e.g., STEP F1/4), (2) output agent completion lines with elapsed time, (3) show a condensed final summary with timing. The format should be consistent with the full pipeline's protocol but adapted for fewer steps.",
            category="completeness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_batch_mode_has_progress(self, genai):
        """implement-batch.md must include per-feature and batch-level progress."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement-batch.md").read_text()
        result = genai.judge(
            question="Does this batch-mode command file include both per-feature progress headers and batch-level summary output?",
            context=content,
            criteria="Batch mode should: (1) show a batch header with total feature count, (2) show per-feature headers with feature number and description, (3) reference the full pipeline's progress protocol for per-step output within each feature, (4) show per-feature timing in the batch summary. The existing STEP B5 summary should be enhanced with timing data.",
            category="completeness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_gate_result_format(self, genai):
        """HARD GATE results must have a clear PASS/BLOCKED format."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does the Pipeline Progress Protocol define a clear format for displaying HARD GATE results (PASS or BLOCKED with reason)?",
            context=content,
            criteria="The protocol should define a gate result format like 'GATE: name — PASS' or 'GATE: name — BLOCKED (reason)'. This format should be referenced at each HARD GATE step (STEP 0.5, STEP 1, STEP 5, STEP 5.5, STEP 8.5, STEP 9). The test gate (STEP 5) should additionally show pass/fail/skip counts and coverage.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
