"""Acceptance tests for: STEP 6.5 Remediation Gate

Generated by acceptance-first pipeline mode.
Validates that the /implement pipeline blocks git operations when reviewer
issues REQUEST_CHANGES or security-auditor issues FAIL, relays findings
to implementer for fixing, and caps remediation at 2 cycles.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceRemediationGate:
    """Acceptance criteria for STEP 6.5 Remediation Gate."""

    def test_step_6_5_exists_between_validation_and_verification(self, genai):
        """STEP 6.5 must exist between STEP 6 (validation) and STEP 7 (verification)."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does this pipeline have a STEP 6.5 Remediation Gate that appears AFTER STEP 6 (Parallel Validation) and BEFORE STEP 7 (Final Verification)?",
            context=content,
            criteria="There must be a section titled 'STEP 6.5' or 'Remediation Gate' that is positioned between the validation step (reviewer/security-auditor) and the verification step. It must be a HARD GATE.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_request_changes_triggers_remediation(self, genai):
        """Reviewer REQUEST_CHANGES must trigger the remediation loop."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="When the reviewer issues REQUEST_CHANGES, does the pipeline enter a remediation loop that re-invokes the implementer with the findings?",
            context=content,
            criteria="The pipeline must detect REQUEST_CHANGES from the reviewer, pass the findings verbatim to the implementer agent, and re-run the reviewer after fixes. It must NOT proceed to git operations with REQUEST_CHANGES unresolved.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_security_fail_triggers_remediation(self, genai):
        """Security-auditor FAIL must trigger the remediation loop."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="When the security-auditor issues FAIL, does the pipeline enter a remediation loop that re-invokes the implementer with the security findings?",
            context=content,
            criteria="The pipeline must detect FAIL from the security-auditor, pass the findings to the implementer, and re-run the security-auditor after fixes. Security FAIL must be treated with at least the same severity as reviewer REQUEST_CHANGES.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_max_2_remediation_cycles(self, genai):
        """Remediation must be limited to 2 cycles maximum."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Is the remediation loop limited to a maximum of 2 cycles before blocking the pipeline?",
            context=content,
            criteria="There must be an explicit maximum of 2 remediation cycles. After 2 failed attempts, the pipeline must BLOCK (not proceed to git operations). The max must be stated as a number, not left ambiguous.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_findings_filed_as_issues_after_max_retries(self, genai):
        """Unresolved findings must be filed as GitHub issues after max retries."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="After 2 failed remediation cycles, does the pipeline file unresolved findings as GitHub issues?",
            context=content,
            criteria="After exhausting 2 remediation cycles, the pipeline must use 'gh issue create' to file unresolved BLOCKING findings as GitHub issues. The issues should include the finding details and the pipeline run context.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_reviewer_has_structured_findings(self, genai):
        """Reviewer must output structured FINDINGS with severity tiers."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/agents/reviewer.md").read_text()
        result = genai.judge(
            question="Does the reviewer agent output structured findings with BLOCKING and WARNING severity levels?",
            context=content,
            criteria="The reviewer must have a structured output format that distinguishes BLOCKING findings (which trigger remediation) from WARNING findings (which are noted but do not block). Each finding must include file:line reference, severity, and suggested fix.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_implementer_has_remediation_mode(self, genai):
        """Implementer must document Remediation Mode behavior."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/agents/implementer.md").read_text()
        result = genai.judge(
            question="Does the implementer agent have a documented Remediation Mode that describes how it should behave when fixing review/security findings?",
            context=content,
            criteria="The implementer must have a section called 'Remediation Mode' that describes: scope is narrower (only fix BLOCKING findings), findings are the spec, tests must pass after fixes, and a FORBIDDEN list preventing feature additions or unrelated refactoring during remediation.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_light_pipeline_unaffected(self, genai):
        """Light pipeline must NOT include remediation gate."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does the light pipeline mode (--light) correctly EXCLUDE the remediation gate? The light pipeline should have no reviewer or security-auditor, so no remediation is needed.",
            context=content,
            criteria="The LIGHT PIPELINE MODE section must NOT contain STEP 6.5, Remediation Gate, or any remediation loop logic. Light mode skips reviewer and security-auditor entirely, so there is nothing to remediate.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
