"""Acceptance tests for: Smart test routing in /implement

Generated by acceptance-first pipeline mode.
Validates that /implement STEP 5 selects test tiers based on changed files,
reports skipped tiers, supports --full-tests override, and uses configurable routing.
"""

import pytest
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceSmartTestRouting:
    """Acceptance criteria for smart test routing (Issue #508)."""

    def test_test_routing_module_exists(self):
        """The test_routing.py library must exist."""
        lib_path = PROJECT_ROOT / "plugins/autonomous-dev/lib/test_routing.py"
        assert lib_path.exists(), f"Missing library: {lib_path}"

    def test_routing_config_exists(self):
        """The test_routing_config.json must exist."""
        config_path = PROJECT_ROOT / "plugins/autonomous-dev/config/test_routing_config.json"
        assert config_path.exists(), f"Missing config: {config_path}"

    def test_routing_config_is_valid_json(self):
        """The routing config must be valid JSON with required structure."""
        config_path = PROJECT_ROOT / "plugins/autonomous-dev/config/test_routing_config.json"
        config = json.loads(config_path.read_text())
        assert "routing_rules" in config, "Config must have routing_rules"
        assert "tier_to_marker" in config, "Config must have tier_to_marker"

    def test_routing_config_covers_all_categories(self):
        """The routing config must have rules for all change categories."""
        config_path = PROJECT_ROOT / "plugins/autonomous-dev/config/test_routing_config.json"
        config = json.loads(config_path.read_text())
        required = {"hook", "agent_prompt", "command", "lib", "config", "skill", "docs_only", "install_sync"}
        actual = set(config["routing_rules"].keys())
        assert required.issubset(actual), f"Missing categories: {required - actual}"

    def test_test_routing_has_required_functions(self):
        """test_routing module must export classify_changes and compute_marker_expression."""
        import ast

        lib_path = PROJECT_ROOT / "plugins/autonomous-dev/lib/test_routing.py"
        tree = ast.parse(lib_path.read_text())
        func_names = [node.name for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)]
        assert "classify_changes" in func_names
        assert "compute_marker_expression" in func_names
        assert "get_skipped_tiers" in func_names

    def test_implement_command_has_full_tests_flag(self, genai):
        """The /implement command must support --full-tests flag."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does this command recognize and handle a --full-tests flag that forces running the complete test suite, bypassing smart test routing?",
            context=content,
            criteria="The command must parse --full-tests as a valid flag and pass it through to the test gate so that smart test routing is disabled when this flag is present.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
