"""Acceptance tests for: SubagentStop hook transcript visibility + duration tracking.

Generated by acceptance-first pipeline mode.
Validates that unified_session_tracker reads stdin JSON (not env vars),
computes duration_ms, writes JSONL for CI agent, and validates transcript paths.

Related tasks: Read agent_transcript_path, fix duration_ms, CI agent visibility.
"""

import json
import re

import pytest

from .conftest import PROJECT_ROOT

pytestmark = [pytest.mark.genai]

PLUGIN_ROOT = PROJECT_ROOT / "plugins" / "autonomous-dev"
TRACKER_PATH = PLUGIN_ROOT / "hooks" / "unified_session_tracker.py"
VALIDATOR_PATH = PLUGIN_ROOT / "lib" / "pipeline_intent_validator.py"


class TestStdinJsonParsing:
    """SubagentStop hook must read from stdin JSON, not environment variables."""

    def test_reads_stdin_not_env_vars(self, genai):
        """The main() function must parse stdin JSON for agent data."""
        source = TRACKER_PATH.read_text()

        # Deterministic: sys.stdin.read() must be present
        assert "sys.stdin.read()" in source or "stdin.read()" in source, (
            "unified_session_tracker does not read stdin — "
            "SubagentStop hooks receive data via stdin JSON, not env vars"
        )

        # GenAI: verify stdin is the primary data source, env vars are fallback only
        result = genai.judge(
            question="Does main() read agent data from stdin JSON as the primary source?",
            context=source,
            criteria=(
                "The main() function should: (1) read from sys.stdin, "
                "(2) parse JSON to get agent_type, agent_transcript_path, "
                "last_assistant_message, (3) only fall back to environment "
                "variables if stdin is empty or unparseable."
            ),
        )
        assert result["pass"], f"Stdin parsing not implemented correctly: {result['reasoning']}"

    def test_extracts_agent_transcript_path(self):
        """Hook must extract agent_transcript_path from stdin JSON."""
        source = TRACKER_PATH.read_text()
        assert "agent_transcript_path" in source, (
            "unified_session_tracker does not reference agent_transcript_path — "
            "CI agent needs transcript paths for full visibility"
        )


class TestDurationComputation:
    """Duration must be computed since SubagentStop input has no duration field."""

    def test_computes_duration_ms(self, genai):
        """Duration must be derived, not read from input."""
        source = TRACKER_PATH.read_text()

        # Deterministic: must compute duration somehow
        has_time_import = "import time" in source or "from time" in source
        has_datetime_calc = "timedelta" in source or "total_seconds" in source
        has_monotonic = "time.monotonic" in source
        assert has_time_import or has_datetime_calc or has_monotonic, (
            "No duration computation found — duration_ms is not in SubagentStop input"
        )

        # GenAI: verify duration is computed correctly
        result = genai.judge(
            question="Does the hook compute agent task duration in milliseconds?",
            context=source,
            criteria=(
                "The hook should compute duration_ms by either: "
                "(1) diffing agent_tracker's started_at against current time, or "
                "(2) using time.monotonic() for hook execution time, or "
                "(3) reading timestamps from the transcript. "
                "The result must be in milliseconds and stored in the JSONL entry."
            ),
        )
        assert result["pass"], f"Duration computation not correct: {result['reasoning']}"


class TestJsonlWriting:
    """SubagentStop must write JSONL entries for CI agent consumption."""

    def test_writes_to_activity_log(self, genai):
        """Hook must write structured JSONL to .claude/logs/activity/."""
        source = TRACKER_PATH.read_text()

        # Deterministic: must write JSONL
        assert "jsonl" in source.lower() or "json.dumps" in source, (
            "unified_session_tracker does not write JSONL — "
            "CI agent reads .claude/logs/activity/ for pipeline analysis"
        )

        # GenAI: verify JSONL entry has required fields
        result = genai.judge(
            question="Does the hook write JSONL entries with all fields needed by pipeline_intent_validator?",
            context=source,
            criteria=(
                "The JSONL entry must include: hook='SubagentStop', "
                "subagent_type, duration_ms, result_word_count, "
                "agent_transcript_path, session_id, and success. "
                "The entry must be appended to .claude/logs/activity/{date}.jsonl."
            ),
        )
        assert result["pass"], f"JSONL writing not complete: {result['reasoning']}"


class TestTranscriptPathValidation:
    """agent_transcript_path must be validated against path traversal."""

    def test_validates_path_security(self, genai):
        """Transcript path must be validated before use."""
        source = TRACKER_PATH.read_text()

        # GenAI: verify path traversal protection
        result = genai.judge(
            question="Does the hook validate agent_transcript_path against path traversal?",
            context=source,
            criteria=(
                "The hook should: (1) resolve the path with Path.resolve(), "
                "(2) verify it starts with an expected prefix (e.g., home dir or .claude), "
                "(3) if validation fails, set to empty string rather than blocking. "
                "Raw user-controlled paths should never be used without validation."
            ),
        )
        assert result["pass"], f"Path validation missing: {result['reasoning']}"


class TestPipelineValidatorIntegration:
    """pipeline_intent_validator must parse SubagentStop JSONL entries."""

    def test_parses_subagent_stop_entries(self, genai):
        """parse_session_logs must handle SubagentStop hook entries."""
        source = VALIDATOR_PATH.read_text()

        # Deterministic: must reference SubagentStop
        assert "SubagentStop" in source, (
            "pipeline_intent_validator does not handle SubagentStop entries — "
            "CI agent cannot see subagent completion data"
        )

        # GenAI: verify parsing creates PipelineEvents with correct data
        result = genai.judge(
            question="Does parse_session_logs handle SubagentStop JSONL entries?",
            context=source,
            criteria=(
                "When a JSONL entry has hook='SubagentStop', parse_session_logs "
                "should create a PipelineEvent with: subagent_type from the entry, "
                "duration_ms from the entry, result_word_count from the entry, "
                "and pipeline_action='agent_completion'."
            ),
        )
        assert result["pass"], f"SubagentStop parsing not implemented: {result['reasoning']}"
