"""Acceptance tests for: Property-based testing expansion

Generated by acceptance-first pipeline mode.
Validates that property-based tests exist for core libs using hypothesis,
tests/property/ directory is properly configured, and pytest marker works.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptancePropertyTesting:
    """Acceptance criteria for property-based testing expansion (Issue #509)."""

    def test_property_directory_exists(self):
        """tests/property/ directory must exist."""
        prop_dir = PROJECT_ROOT / "tests/property"
        assert prop_dir.is_dir(), f"Missing directory: {prop_dir}"

    def test_property_conftest_exists(self):
        """tests/property/conftest.py must exist."""
        conftest = PROJECT_ROOT / "tests/property/conftest.py"
        assert conftest.exists(), f"Missing conftest: {conftest}"

    def test_security_utils_properties_exist(self):
        """Property tests for security_utils must exist."""
        test_file = PROJECT_ROOT / "tests/property/test_security_utils_properties.py"
        assert test_file.exists(), f"Missing: {test_file}"
        content = test_file.read_text()
        assert "from hypothesis" in content, "Must use hypothesis"
        assert "@given" in content, "Must use @given decorator"

    def test_pipeline_state_properties_exist(self):
        """Property tests for pipeline_state must exist."""
        test_file = PROJECT_ROOT / "tests/property/test_pipeline_state_properties.py"
        assert test_file.exists(), f"Missing: {test_file}"
        content = test_file.read_text()
        assert "from hypothesis" in content, "Must use hypothesis"
        assert "@given" in content, "Must use @given decorator"

    def test_tool_validator_properties_exist(self):
        """Property tests for tool_validator must exist."""
        test_file = PROJECT_ROOT / "tests/property/test_tool_validator_properties.py"
        assert test_file.exists(), f"Missing: {test_file}"
        content = test_file.read_text()
        assert "from hypothesis" in content, "Must use hypothesis"
        assert "@given" in content, "Must use @given decorator"

    def test_property_marker_in_pytest_ini(self):
        """The 'property' marker must be registered in pytest.ini."""
        ini_path = PROJECT_ROOT / "pytest.ini"
        content = ini_path.read_text()
        assert "property" in content, "property marker must be in pytest.ini"

    def test_property_tests_use_real_code(self, genai):
        """Property tests must exercise real library code, not mocks."""
        test_files = [
            PROJECT_ROOT / "tests/property/test_security_utils_properties.py",
            PROJECT_ROOT / "tests/property/test_pipeline_state_properties.py",
            PROJECT_ROOT / "tests/property/test_tool_validator_properties.py",
        ]
        combined = "\n".join(f.read_text() for f in test_files if f.exists())
        result = genai.judge(
            question="Do these property tests call real library functions (from security_utils, pipeline_state, tool_validator) rather than mocking the functions under test?",
            context=combined[:5000],
            criteria="Property tests must import and call the actual library functions they are testing. They should NOT mock the function under test (mocking dependencies is acceptable). The tests should use @given with hypothesis strategies to generate inputs and verify invariants against the real code.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
