"""Acceptance tests for: Issue #491 — Block /implement when pre-staged files detected

Generated by acceptance-first pipeline mode.
Validates that all three /implement pipeline variants (full, fix, batch)
include a HARD GATE that detects pre-staged git files and blocks execution.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptancePreStagedGate:
    """Acceptance criteria from planner output for Issue #491."""

    def test_implement_has_pre_staged_gate(self, genai):
        """Main pipeline must check for pre-staged files before any work."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does this pipeline command include a HARD GATE that checks for pre-staged git files (via git diff --cached) BEFORE the PROJECT.md alignment check or any agent work begins?",
            context=content,
            criteria="There must be a step that runs 'git diff --cached --name-only' (or equivalent) and BLOCKs the pipeline if any files are already staged. It must appear BEFORE STEP 1 (PROJECT.md alignment). It must include FORBIDDEN markers and offer resolution options (unstage, commit first, review).",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_implement_fix_has_pre_staged_gate(self, genai):
        """Fix pipeline must check for pre-staged files."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement-fix.md").read_text()
        result = genai.judge(
            question="Does this fix pipeline command include a check for pre-staged git files (via git diff --cached) that blocks execution if staged files are found?",
            context=content,
            criteria="There must be a step that checks for pre-staged files using 'git diff --cached' and BLOCKs if any are found. It must include FORBIDDEN markers preventing silent bypass.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_implement_batch_has_pre_staged_gate(self, genai):
        """Batch pipeline must check for pre-staged files before worktree creation."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement-batch.md").read_text()
        result = genai.judge(
            question="Does this batch pipeline command include a check for pre-staged git files BEFORE worktree creation that blocks execution if staged files are found?",
            context=content,
            criteria="There must be a step that checks for pre-staged files using 'git diff --cached' BEFORE the worktree creation step (STEP B1). Pre-staged files would propagate into worktrees. It must include FORBIDDEN markers.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_gate_does_not_auto_fix(self, genai):
        """Gate must NOT silently unstage or commit files."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does the pre-staged files gate avoid automatically fixing the problem (no auto-unstaging, no auto-committing)?",
            context=content,
            criteria="The gate must BLOCK and present options to the user. It must NOT run 'git reset HEAD' or 'git commit' automatically. The FORBIDDEN list must explicitly prohibit silently unstaging files without user confirmation.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
