"""Acceptance tests for: Doc-Master Semantic Drift Detection

Generated by acceptance-first pipeline mode.
Validates that the doc-master agent detects semantic documentation drift
using covers: frontmatter tagging, outputs structured PASS/FAIL verdicts,
and blocks the pipeline before git operations.
"""

import pytest
import yaml
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceDocDriftDetection:
    """Acceptance criteria for doc-master semantic drift detection."""

    def test_doc_master_does_not_reference_claude_md(self, genai):
        """Doc-master must NOT update or reference CLAUDE.md as part of its scope."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/agents/doc-master.md").read_text()
        result = genai.judge(
            question="Does this agent definition include CLAUDE.md as part of its documentation update scope?",
            context=content,
            criteria="The agent must NOT list CLAUDE.md as a file it updates, manages, or validates. CLAUDE.md is handled by the alignment system, not doc-master. References to CLAUDE.md in examples or exclusion lists are acceptable, but it must not be in the agent's active scope.",
            category="correctness",
        )
        # We want it to NOT reference CLAUDE.md, so pass means "no, it doesn't"
        assert "claude.md" not in content.lower().split("## core responsibilities")[0] or result["band"] != "hard_fail", result["reasoning"]

    def test_doc_master_uses_covers_frontmatter(self, genai):
        """Doc-master must use covers: frontmatter to find affected docs."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/agents/doc-master.md").read_text()
        result = genai.judge(
            question="Does this agent use 'covers:' YAML frontmatter from docs/*.md files to determine which documentation files are affected by code changes?",
            context=content,
            criteria="The agent must parse 'covers:' frontmatter from documentation files to build a mapping between source code paths and the docs that describe them. It must intersect changed files with these mappings to find affected docs. Simple grep-based sweeps are not sufficient.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_doc_master_outputs_structured_verdict(self, genai):
        """Doc-master must output a structured DOC-DRIFT-VERDICT."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/agents/doc-master.md").read_text()
        result = genai.judge(
            question="Does this agent output a structured verdict in the format DOC-DRIFT-VERDICT: PASS or DOC-DRIFT-VERDICT: FAIL with specific findings?",
            context=content,
            criteria="The agent must output a clearly parseable verdict string 'DOC-DRIFT-VERDICT: PASS' or 'DOC-DRIFT-VERDICT: FAIL' at the end of its response. FAIL verdicts must include specific findings listing the doc file, the inaccurate claim, and the actual behavior from source code.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_doc_master_performs_semantic_comparison(self, genai):
        """Doc-master must compare doc content against source code semantically."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/agents/doc-master.md").read_text()
        result = genai.judge(
            question="Does this agent perform semantic comparison between documentation prose and actual source code behavior, not just structural checks like counts or cross-references?",
            context=content,
            criteria="The agent must read both the documentation file and the source code it covers, then evaluate whether the doc's descriptions, claims, and explanations accurately reflect the current code behavior. This is a semantic/meaning-level comparison, not just checking if file paths exist or counts match.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_pipeline_blocks_on_doc_drift(self, genai):
        """Pipeline must block before git operations if doc-master reports FAIL."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does the pipeline block before git operations (STEP 8) when doc-master reports a FAIL verdict with unfixed findings?",
            context=content,
            criteria="There must be a collection/blocking point AFTER doc-master runs and BEFORE git commit/push that checks the doc-master verdict. If DOC-DRIFT-VERDICT is FAIL with unfixed findings, the pipeline must BLOCK. The doc-master can launch in the background for parallelism, but its result must be collected and enforced before proceeding.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_doc_master_launches_parallel_with_reviewer(self, genai):
        """Doc-master should launch in parallel with reviewer for efficiency."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does doc-master launch in parallel with the reviewer agent (in the background) during validation, rather than running sequentially after all other validators?",
            context=content,
            criteria="Doc-master must be invoked with run_in_background=true during the validation step (STEP 6), launching at the same time as or before the reviewer. This allows doc-master to work while reviewer and security-auditor complete, maximizing parallelism.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]


class TestDocsFrontmatterCovers:
    """Structural tests: all docs/*.md files have valid covers: frontmatter."""

    DOCS_DIR = PROJECT_ROOT / "docs"
    # Files that should have covers: frontmatter
    EXPECTED_DOCS = [
        "ARCHITECTURE-OVERVIEW.md",
        "HOOKS.md",
        "HOOK-REGISTRY.md",
        "AGENTS.md",
        "LIBRARIES.md",
        "WORKFLOW-DISCIPLINE.md",
        "TESTING-STRATEGY.md",
        "BATCH-PROCESSING.md",
        "GIT-AUTOMATION.md",
        "SANDBOXING.md",
        "PERFORMANCE.md",
        "CONTEXT-MANAGEMENT.md",
        "MCP-ARCHITECTURE.md",
        "MCP-SECURITY.md",
        "SECURITY.md",
        "TOOL-AUTO-APPROVAL.md",
        "ACCOUNTABILITY-HOOKS.md",
        "GITHUB-ACTIONS.md",
        "CLAUDE-MEM-INTEGRATION.md",
        "MAINTAINING-PHILOSOPHY.md",
        "ADR-001-agent-hooks.md",
    ]

    def _parse_frontmatter(self, file_path: Path) -> dict:
        """Parse YAML frontmatter from a markdown file."""
        content = file_path.read_text()
        if not content.startswith("---"):
            return {}
        end = content.index("---", 3)
        frontmatter_text = content[3:end].strip()
        return yaml.safe_load(frontmatter_text) or {}

    def test_all_docs_have_frontmatter(self):
        """Every docs/*.md file in EXPECTED_DOCS must have YAML frontmatter."""
        missing = []
        for doc_name in self.EXPECTED_DOCS:
            doc_path = self.DOCS_DIR / doc_name
            if not doc_path.exists():
                missing.append(f"{doc_name}: file does not exist")
                continue
            content = doc_path.read_text()
            if not content.startswith("---"):
                missing.append(f"{doc_name}: no YAML frontmatter")
        assert not missing, f"Docs missing frontmatter:\n" + "\n".join(missing)

    def test_all_docs_have_covers_key(self):
        """Every docs/*.md frontmatter must contain a 'covers' key."""
        missing = []
        for doc_name in self.EXPECTED_DOCS:
            doc_path = self.DOCS_DIR / doc_name
            if not doc_path.exists():
                continue
            fm = self._parse_frontmatter(doc_path)
            if "covers" not in fm:
                missing.append(doc_name)
        assert not missing, f"Docs missing 'covers' key in frontmatter:\n" + "\n".join(missing)

    def test_covers_paths_are_valid(self):
        """All paths in covers: must point to existing files or directories."""
        invalid = []
        for doc_name in self.EXPECTED_DOCS:
            doc_path = self.DOCS_DIR / doc_name
            if not doc_path.exists():
                continue
            fm = self._parse_frontmatter(doc_path)
            covers = fm.get("covers", [])
            if not covers:
                continue
            for path_str in covers:
                full_path = PROJECT_ROOT / path_str
                if not full_path.exists():
                    invalid.append(f"{doc_name}: {path_str} does not exist")
        assert not invalid, f"Invalid covers paths:\n" + "\n".join(invalid)

    def test_covers_values_are_lists(self):
        """covers: must be a list, not a string or other type."""
        bad_types = []
        for doc_name in self.EXPECTED_DOCS:
            doc_path = self.DOCS_DIR / doc_name
            if not doc_path.exists():
                continue
            fm = self._parse_frontmatter(doc_path)
            covers = fm.get("covers")
            if covers is not None and not isinstance(covers, list):
                bad_types.append(f"{doc_name}: covers is {type(covers).__name__}, expected list")
        assert not bad_types, f"Bad covers types:\n" + "\n".join(bad_types)
