"""Acceptance tests for: Issue #528 — Enforce /implement hard block when explicitly invoked

Generated by acceptance-first pipeline mode.
Validates that when /implement is explicitly invoked, the coordinator is hard-blocked
from writing code directly — only pipeline agents can write. Applies to external repos too.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceExplicitImplementBlock:
    """Acceptance criteria from Issue #528."""

    def test_explicit_implement_detection_exists(self, genai):
        """Hook must detect when /implement was explicitly invoked via state file flag."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="Does this hook have a function that checks the pipeline state file for an 'explicitly_invoked' flag?",
            context=content,
            criteria="There must be a function (e.g., _is_explicit_implement_active) that reads the pipeline state file (/tmp/implement_pipeline_state.json), checks for an 'explicitly_invoked' field set to true, AND validates the session_start timestamp is within 2 hours (TTL). Must return bool.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_coordinator_blocked_during_explicit_implement(self, genai):
        """Coordinator Write/Edit must be denied when explicit /implement is active."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="When the pipeline state file has explicitly_invoked=true and the caller is NOT a pipeline agent, are Write/Edit to code files denied?",
            context=content,
            criteria="The hook must return a 'deny' decision when: (1) explicitly_invoked is true in state file, (2) CLAUDE_AGENT_NAME is not in PIPELINE_AGENTS (implementer/test-master/doc-master), (3) the tool is Write/Edit targeting a code file, (4) ENFORCEMENT_LEVEL is not 'off'. The deny must happen in BOTH the native tools fast path AND validate_agent_authorization.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_pipeline_agents_bypass_explicit_block(self, genai):
        """Pipeline agents (implementer, test-master, doc-master) must still be allowed."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="When explicit /implement is active AND the caller IS a pipeline agent, are Write/Edit allowed?",
            context=content,
            criteria="Pipeline agents listed in PIPELINE_AGENTS must be allowed to write code even when explicit /implement is active. The check for agent name in PIPELINE_AGENTS must happen BEFORE the explicit implement block.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_external_repo_enforcement(self, genai):
        """External repos (no .claude/commands/implement.md) must also be enforced."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="Does the explicit /implement hard block work in external repos that don't have .claude/commands/implement.md?",
            context=content,
            criteria="The explicit /implement enforcement must NOT depend on _is_autonomous_dev_repo() returning true. The check in the native tools fast path must fire based on the state file flag alone, independent of whether the repo has the autonomous-dev marker file.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_enforcement_off_overrides(self, genai):
        """ENFORCEMENT_LEVEL=off must still work as escape hatch."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="When ENFORCEMENT_LEVEL=off, does the explicit /implement hard block get bypassed?",
            context=content,
            criteria="Even when explicitly_invoked=true in the state file, if ENFORCEMENT_LEVEL is set to 'off', all code writes must be allowed. The off check must appear in the enforcement path before the deny decision.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_state_file_includes_explicit_flag(self, genai):
        """implement.md must write explicitly_invoked:true to state file."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does the /implement command's STEP 0 write 'explicitly_invoked' to the pipeline state JSON file?",
            context=content,
            criteria="The echo/write command that creates /tmp/implement_pipeline_state.json must include 'explicitly_invoked':true (or equivalent) in the JSON payload. This flag distinguishes explicit user invocation from other pipeline states.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_deny_message_says_delegate(self, genai):
        """Deny message must tell coordinator to delegate, not to run /implement."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="When the coordinator is blocked during explicit /implement, does the deny message instruct delegation to pipeline agents?",
            context=content,
            criteria="The deny reason/message must tell the coordinator to delegate work to pipeline agents (implementer, test-master, doc-master) — NOT to 'run /implement' since it's already running. The message should mention 'WORKFLOW ENFORCEMENT' and reference the pipeline agents by name.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
