"""Acceptance tests for: Hook extension points system

Generated by acceptance-first pipeline mode.
Validates that unified_pre_tool.py supports loading extension files from
.claude/hooks/extensions/*.py and that install/sync preserves the extensions directory.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceHookExtensions:
    """Acceptance criteria for hook extension points system."""

    def test_run_extensions_function_exists(self, genai):
        """Hook must have a _run_extensions function that loads extension files."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="Does this hook define a _run_extensions function that discovers and loads .py files from an extensions directory?",
            context=content,
            criteria="There must be a _run_extensions(tool_name, tool_input) function that: 1) looks for .py files in a hooks/extensions/ directory, 2) loads them via importlib, 3) calls their check() function, 4) returns ('deny', reason) if any extension denies, or ('allow', '') if all pass.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_extensions_crash_isolation(self, genai):
        """Extensions must never crash the hook."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="Does the _run_extensions function isolate each extension with try/except so a crashing extension cannot crash the hook?",
            context=content,
            criteria="Each extension must be loaded and executed inside a try/except block. If an extension raises any exception, it must be caught and the hook must continue processing other extensions or return allow. The hook must NEVER propagate an exception from an extension.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_extensions_integrated_in_main(self, genai):
        """Extensions must be called in the main dispatch flow."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="Is _run_extensions called in the main() function's dispatch flow so that extensions can block both native and non-native tool calls?",
            context=content,
            criteria="The main() function must call _run_extensions at appropriate points: 1) in the native tool path (after infrastructure protection but before returning allow), and 2) in the non-native tool path (so extension deny results participate in the final decision). Extensions must be able to block ANY tool call, not just non-native tools.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_extensions_env_var_disable(self, genai):
        """Extensions must be disableable via environment variable."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="Can extensions be disabled via an environment variable like HOOK_EXTENSIONS_ENABLED?",
            context=content,
            criteria="There must be an environment variable check that, when set to 'false', causes _run_extensions to return ('allow', '') immediately without loading any extensions. This serves as a kill switch for debugging.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_install_preserves_extensions(self, genai):
        """install.sh must preserve the extensions directory."""
        content = (PROJECT_ROOT / "install.sh").read_text()
        result = genai.judge(
            question="Does install.sh ensure that ~/.claude/hooks/extensions/ is preserved or created during installation?",
            context=content,
            criteria="The install script must either: 1) explicitly create the extensions directory (mkdir -p), or 2) have logic that avoids deleting it during hook file cleanup. The extensions directory must survive a fresh install or update.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_extension_api_documented(self, genai):
        """The extension API must be documented."""
        content = (PROJECT_ROOT / "docs/HOOKS.md").read_text()
        result = genai.judge(
            question="Does HOOKS.md document the extension points system including the API contract, directory locations, and an example?",
            context=content,
            criteria="The documentation must include: 1) the extension directory path(s), 2) the check(tool_name, tool_input) function signature and return type, 3) at least one example extension, 4) how extensions survive sync/install, 5) the HOOK_EXTENSIONS_ENABLED env var.",
            category="documentation",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
