"""Acceptance tests for: Issue #543 — DOC-VERDICT-MISSING fallback for doc-master timeout/no-output.

Generated by acceptance-first pipeline mode.
Validates feature intent using LLM-as-judge evaluation.
"""
import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceDocVerdictMissing:
    """Acceptance criteria from planner output for Issue #543."""

    def test_detect_doc_verdict_missing_function_exists(self, genai):
        """pipeline_intent_validator must have a function that detects
        doc-master events with zero output."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does this module contain a function that detects doc-master agent events with zero or missing output?",
            context=context,
            criteria="Must have a function (named something like detect_doc_verdict_missing) that filters for doc-master agent events and flags those with result_word_count == 0 or has_output == false as WARNING findings.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_detection_wired_into_orchestrator(self, genai):
        """detect_doc_verdict_missing must be called from validate_pipeline_intent()."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does validate_pipeline_intent() call a doc-verdict-missing detection function?",
            context=context,
            criteria="The validate_pipeline_intent() function must call detect_doc_verdict_missing (or equivalent) and extend its findings list with the results.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_step12_has_retry_protocol(self, genai):
        """implement.md STEP 12 must include retry-with-reduced-context for empty doc-master output."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md").read_text()
        result = genai.judge(
            question="Does the doc-drift collection point (STEP 12 or equivalent) include a retry mechanism for doc-master empty output?",
            context=context,
            criteria="When doc-master returns empty output or no verdict, the coordinator must retry once with reduced context before logging DOC-VERDICT-MISSING as a warning. Should not just silently proceed on first failure.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_ci_analyst_references_programmatic_detection(self, genai):
        """continuous-improvement-analyst Check 9 must reference the programmatic detection function."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/agents/continuous-improvement-analyst.md").read_text()
        result = genai.judge(
            question="Does the continuous-improvement-analyst's doc-master verdict quality check reference a programmatic detection function?",
            context=context,
            criteria="Check 9 (or the doc-master verdict quality check) should reference detect_doc_verdict_missing or pipeline_intent_validator as a programmatic detection mechanism, connecting manual log scanning with automated detection.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
