"""Acceptance tests for: Issue #483 — Block direct edits to infrastructure files without /implement

Generated by acceptance-first pipeline mode.
Validates that unified_pre_tool.py blocks Write/Edit to infrastructure files
(agents/, commands/, hooks/, lib/, skills/) unless /implement pipeline is active.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceInfrastructureProtection:
    """Acceptance criteria from planner output for Issue #483."""

    def test_protected_file_check_exists(self, genai):
        """Hook must have infrastructure protection logic before native tools bypass."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="Does this hook check whether Write/Edit targets an infrastructure file BEFORE the native tools fast-path bypass returns 'allow'?",
            context=content,
            criteria="There must be a check that fires for Write/Edit tools targeting agents/*.md, commands/*.md, hooks/*.py, lib/*.py, or skills/*/SKILL.md BEFORE the generic native tools 'allow' return. The check must happen in the main() function's native tools block, not in a validation layer that gets bypassed.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_pipeline_bypass_works(self, genai):
        """Pipeline agents must be allowed through the protection."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="Does the infrastructure protection allow pipeline agents (implementer, test-master, doc-master) to bypass the block?",
            context=content,
            criteria="When CLAUDE_AGENT_NAME is set to a pipeline agent name (implementer, test-master, doc-master) or a valid pipeline state file exists, Write/Edit to infrastructure files must be allowed. The bypass must check both the environment variable AND the state file.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_deny_includes_user_message(self, genai):
        """Blocked edits must include user-visible systemMessage."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="When an infrastructure file edit is blocked, does the deny response include both a permissionDecisionReason (model-visible) AND a systemMessage (user-visible)?",
            context=content,
            criteria="The deny output must include a systemMessage field in the JSON so the user can see why the edit was blocked. permissionDecisionReason alone is only model-visible and gives the user zero visibility. The message should mention /implement as the correct approach.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_non_infra_files_unaffected(self, genai):
        """Protection must not block non-infrastructure files."""
        content = (PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py").read_text()
        result = genai.judge(
            question="Does the infrastructure protection correctly exclude non-infrastructure files like src/*.py, tests/*.py, README.md, config files, and documentation?",
            context=content,
            criteria="The protection must ONLY block files in agents/, commands/, hooks/, lib/, and skills/ directories with appropriate extensions (.md for agents/commands/skills, .py for hooks/lib). Files like README.md, CHANGELOG.md, tests/test_foo.py, src/app.py, and .json/.yaml config files must NOT be blocked.",
            category="correctness",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
