"""Acceptance tests for: Issue #544 — Progressive prompt compression detection in batch.

Generated by acceptance-first pipeline mode.
Validates feature intent using LLM-as-judge evaluation.
"""
import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptancePromptCompression:
    """Acceptance criteria from planner output for Issue #544."""

    def test_progressive_compression_detection_exists(self, genai):
        """The pipeline_intent_validator must have a function that detects
        cross-issue progressive prompt compression in batch sessions."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does this module contain a function that detects progressive prompt compression across batch issues?",
            context=context,
            criteria="Must have a function (named something like detect_progressive_compression) that groups agent events by batch issue number, compares prompt word counts across issues for the same agent type, and flags when prompts shrink beyond a threshold.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_minimum_prompt_violation_detection_exists(self, genai):
        """The pipeline_intent_validator must have a function that enforces
        minimum prompt word counts for security-critical agents."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does this module contain a function that enforces minimum prompt word counts for security-critical agents?",
            context=context,
            criteria="Must have a function (named something like detect_minimum_prompt_violation) that checks if security-critical agents (security-auditor, reviewer) receive prompts below an absolute minimum word count threshold and flags them as critical violations.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_batch_issue_number_tracked_in_events(self, genai):
        """PipelineEvent must include batch_issue_number field for cross-issue tracking."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does the PipelineEvent data model include a batch_issue_number field?",
            context=context,
            criteria="The PipelineEvent dataclass must have a batch_issue_number field (int, default 0) that is populated from session logs when parsing agent events in batch mode.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_security_critical_agents_defined(self, genai):
        """The module must define which agents are security-critical for compression checks."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does this module define a set of security-critical agents that require compression protection?",
            context=context,
            criteria="Must define a constant (set or list) containing at minimum 'security-auditor' and 'reviewer' as agents whose prompts must not be excessively compressed. Should be used by both the progressive compression and minimum prompt detection functions.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_new_functions_integrated_into_orchestrator(self, genai):
        """Both new detection functions must be called from validate_pipeline_intent()."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/pipeline_intent_validator.py").read_text()
        result = genai.judge(
            question="Does validate_pipeline_intent() call both the progressive compression detection and minimum prompt violation detection functions?",
            context=context,
            criteria="The validate_pipeline_intent() orchestrator function must call both new detection functions and extend its findings list with their results, so that all callers automatically get the enhanced analysis.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_batch_command_has_prompt_integrity_rules(self, genai):
        """implement-batch.md must include FORBIDDEN rules against prompt compression."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement-batch.md").read_text()
        result = genai.judge(
            question="Does this batch command definition include enforcement rules against progressive prompt compression?",
            context=context,
            criteria="Must include a HARD GATE or FORBIDDEN section that explicitly prohibits: passing progressively shorter prompts to security-auditor or reviewer in later batch issues, omitting diff context due to context pressure, and summarizing implementer output for validation agents when full output was passed in earlier issues.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
