#!/usr/bin/env python3
"""Automated reviewer improvement loop: benchmark -> analyze -> improve -> verify.

Runs a baseline benchmark, identifies weaknesses, generates improvement
instructions, applies them to reviewer.md, runs a verification benchmark,
and checks for regressions.

Usage:
    python scripts/improve_reviewer.py \
        --dataset tests/benchmarks/reviewer/dataset.json \
        --model claude-sonnet-4-20250514 \
        --trials 3 \
        --dry-run

GitHub Issue: #578
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# Add lib to path
_LIB_DIR = Path(__file__).resolve().parents[1] / "plugins" / "autonomous-dev" / "lib"
sys.path.insert(0, str(_LIB_DIR))

from benchmark_history import BenchmarkHistory, compute_prompt_hash
from reviewer_weakness_analyzer import (
    WeaknessReport,
    analyze_weaknesses,
    generate_improvement_instructions,
)


def _auto_detect_reviewer_path() -> Path:
    """Auto-detect the reviewer.md path relative to this script.

    Returns:
        Path to the reviewer agent markdown file
    """
    return (
        Path(__file__).resolve().parents[1]
        / "plugins"
        / "autonomous-dev"
        / "agents"
        / "reviewer.md"
    )


def _auto_detect_taxonomy_path(dataset_path: Path) -> Path:
    """Auto-detect taxonomy.json path relative to dataset.

    Args:
        dataset_path: Path to the benchmark dataset

    Returns:
        Path to taxonomy.json
    """
    return dataset_path.parent / "taxonomy.json"


def check_regression(
    baseline_report: Any,
    current_report: Any,
    *,
    threshold: float = 0.05,
    min_samples: int = 3,
) -> Tuple[bool, List[str]]:
    """Check if current benchmark has regressed from baseline.

    Compares per_defect_category accuracy between baseline and current.
    Any category that drops by more than threshold AND has >= min_samples
    is a regression.

    Args:
        baseline_report: The baseline ScoringReport
        current_report: The current ScoringReport after improvements
        threshold: Maximum allowed accuracy drop per category (default: 0.05)
        min_samples: Minimum samples for a category to matter (default: 3)

    Returns:
        Tuple of (regressed: bool, reasons: List[str])
    """
    baseline_cats = getattr(baseline_report, "per_defect_category", {}) or {}
    current_cats = getattr(current_report, "per_defect_category", {}) or {}

    reasons: List[str] = []
    for cat, baseline_stats in baseline_cats.items():
        if not isinstance(baseline_stats, dict):
            continue
        baseline_total = baseline_stats.get("total", 0)
        if baseline_total < min_samples:
            continue

        baseline_acc = baseline_stats.get("accuracy", 0.0)

        current_stats = current_cats.get(cat, {})
        if not isinstance(current_stats, dict):
            # Category disappeared -- treat as regression if it had samples
            reasons.append(
                f"{cat}: disappeared from results (was {baseline_acc:.1%})"
            )
            continue

        current_acc = current_stats.get("accuracy", 0.0)
        drop = baseline_acc - current_acc

        if drop > threshold:
            reasons.append(
                f"{cat}: dropped from {baseline_acc:.1%} to {current_acc:.1%} "
                f"(delta: {drop:.1%}, threshold: {threshold:.1%})"
            )

    return (len(reasons) > 0, reasons)


def apply_improvement(
    reviewer_path: Path,
    instructions: List[str],
    *,
    content: Optional[str] = None,
) -> str:
    """Apply improvement instructions to reviewer.md.

    Finds the '## Learned Patterns' section and replaces its content.
    If the section doesn't exist, inserts before '## Checkpoint Integration'
    or at end.

    Args:
        reviewer_path: Path to reviewer.md
        instructions: List of instruction strings to insert
        content: Optional pre-loaded content (used for testing)

    Returns:
        The updated content string
    """
    if content is None:
        content = reviewer_path.read_text()

    # Build the new section content
    section_lines = [
        "## Learned Patterns",
        "",
        "<!-- Auto-generated by scripts/improve_reviewer.py based on benchmark analysis. -->",
        "<!-- Do not edit manually -- re-run the improvement loop to update. -->",
        "",
    ]
    for i, instruction in enumerate(instructions, 1):
        section_lines.append(f"{i}. {instruction}")
    section_lines.append("")

    new_section = "\n".join(section_lines)

    # Try to find and replace existing ## Learned Patterns section
    learned_pattern = re.compile(
        r"(## Learned Patterns\n)(.*?)(?=\n## |\Z)",
        re.DOTALL,
    )
    match = learned_pattern.search(content)
    if match:
        updated = content[: match.start()] + new_section + content[match.end() :]
    else:
        # Insert before ## Checkpoint Integration if it exists
        checkpoint_idx = content.find("## Checkpoint Integration")
        if checkpoint_idx != -1:
            updated = (
                content[:checkpoint_idx] + new_section + "\n" + content[checkpoint_idx:]
            )
        else:
            # Append at end
            updated = content.rstrip() + "\n\n" + new_section

    return updated


def revert_reviewer(reviewer_path: Path, original_content: str) -> None:
    """Revert reviewer.md to its original content.

    Args:
        reviewer_path: Path to reviewer.md
        original_content: The original content to restore
    """
    reviewer_path.write_text(original_content)


def main() -> None:
    """Run the automated reviewer improvement loop."""
    parser = argparse.ArgumentParser(
        description="Automated reviewer improvement loop (benchmark -> analyze -> improve -> verify)"
    )
    parser.add_argument(
        "--dataset",
        type=Path,
        required=True,
        help="Path to benchmark dataset JSON",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="claude-sonnet-4-20250514",
        help="Anthropic model to use (default: claude-sonnet-4-20250514)",
    )
    parser.add_argument(
        "--trials",
        type=int,
        default=3,
        help="Number of trials per sample (default: 3)",
    )
    parser.add_argument(
        "--reviewer",
        type=Path,
        default=None,
        help="Path to reviewer.md (default: auto-detect)",
    )
    parser.add_argument(
        "--store",
        type=Path,
        default=None,
        help="Path to BenchmarkStore JSON for persistence",
    )
    parser.add_argument(
        "--history",
        type=Path,
        default=None,
        help="Path to JSONL history file for trend tracking",
    )
    parser.add_argument(
        "--max-instructions",
        type=int,
        default=3,
        help="Maximum improvement instructions to generate (default: 3)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would change without modifying files",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.05,
        help="Regression threshold per category (default: 0.05)",
    )
    parser.add_argument(
        "--no-commit",
        action="store_true",
        default=False,
        help="Skip git commit even if improvements accepted",
    )

    args = parser.parse_args()

    # Resolve paths
    reviewer_path = args.reviewer or _auto_detect_reviewer_path()
    taxonomy_path = _auto_detect_taxonomy_path(args.dataset)

    if not args.dataset.exists():
        print(f"ERROR: Dataset not found: {args.dataset}", file=sys.stderr)
        sys.exit(1)

    if not reviewer_path.exists():
        print(f"ERROR: Reviewer not found: {reviewer_path}", file=sys.stderr)
        sys.exit(1)

    # Load taxonomy
    taxonomy: Dict[str, Any] = {}
    if taxonomy_path.exists():
        taxonomy = json.loads(taxonomy_path.read_text())
        print(f"Loaded taxonomy from {taxonomy_path}")
    else:
        print(f"WARNING: No taxonomy found at {taxonomy_path}", file=sys.stderr)

    # Load dataset
    from reviewer_benchmark import load_dataset, score_results, build_reviewer_prompt, parse_verdict, BenchmarkResult

    print(f"Loading dataset from {args.dataset}...")
    samples = load_dataset(args.dataset)
    print(f"Loaded {len(samples)} samples")

    # Load reviewer instructions
    reviewer_content = reviewer_path.read_text()
    prompt_hash = compute_prompt_hash(reviewer_content)

    # Validate API key
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print(
            "ERROR: ANTHROPIC_API_KEY environment variable is not set.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Step 1: Run baseline benchmark
    print("\n=== STEP 1: Running baseline benchmark ===")
    baseline_results = _run_benchmark(
        samples, reviewer_content, model=args.model, trials=args.trials, api_key=api_key
    )
    baseline_report = score_results(baseline_results, samples=samples)
    print(f"Baseline balanced accuracy: {baseline_report.balanced_accuracy:.3f}")

    # Store baseline in history
    if args.history:
        history = BenchmarkHistory(args.history)
        history.append(
            baseline_report,
            prompt_hash=prompt_hash,
            model=args.model,
            metadata={"phase": "baseline"},
        )
        print(f"Baseline stored in history: {args.history}")

    # Step 2: Analyze weaknesses
    print("\n=== STEP 2: Analyzing weaknesses ===")
    weakness_report = analyze_weaknesses(
        baseline_report,
        samples=samples,
        taxonomy=taxonomy,
        threshold=0.70,
        min_samples=3,
    )

    if not weakness_report.items:
        print("No weaknesses found below threshold. No improvements needed.")
        sys.exit(0)

    print(f"Found {len(weakness_report.items)} weak categories:")
    for item in weakness_report.items:
        print(f"  {item.category}: {item.accuracy:.1%} ({item.severity})")

    # Step 3: Generate improvement instructions
    print("\n=== STEP 3: Generating improvement instructions ===")
    instructions = generate_improvement_instructions(
        weakness_report, max_instructions=args.max_instructions
    )
    for i, inst in enumerate(instructions, 1):
        print(f"  {i}. {inst}")

    if args.dry_run:
        print("\n=== DRY RUN: Would apply the above instructions to reviewer.md ===")
        updated = apply_improvement(reviewer_path, instructions, content=reviewer_content)
        print("\n--- Updated Learned Patterns section ---")
        # Show just the relevant section
        start = updated.find("## Learned Patterns")
        if start != -1:
            end = updated.find("\n## ", start + 1)
            section = updated[start:end] if end != -1 else updated[start:]
            print(section)
        print("\n=== DRY RUN complete. No files modified. ===")
        sys.exit(0)

    # Step 4: Apply improvements
    print("\n=== STEP 4: Applying improvements to reviewer.md ===")
    original_content = reviewer_content
    updated_content = apply_improvement(reviewer_path, instructions, content=reviewer_content)
    reviewer_path.write_text(updated_content)
    updated_hash = compute_prompt_hash(updated_content)
    print("Reviewer.md updated with Learned Patterns section")

    # Step 5: Run verification benchmark
    print("\n=== STEP 5: Running verification benchmark ===")
    verify_results = _run_benchmark(
        samples, updated_content, model=args.model, trials=args.trials, api_key=api_key
    )
    verify_report = score_results(verify_results, samples=samples)
    print(f"Verification balanced accuracy: {verify_report.balanced_accuracy:.3f}")

    # Store verification in history
    if args.history:
        history = BenchmarkHistory(args.history)
        history.append(
            verify_report,
            prompt_hash=updated_hash,
            model=args.model,
            metadata={"phase": "verification"},
        )

    # Step 6: Check regression
    print("\n=== STEP 6: Checking for regressions ===")
    regressed, reasons = check_regression(
        baseline_report, verify_report, threshold=args.threshold
    )

    if regressed:
        print("REGRESSION DETECTED! Reverting reviewer.md.")
        for reason in reasons:
            print(f"  - {reason}")
        revert_reviewer(reviewer_path, original_content)
        print("Reviewer.md reverted to original.")
        sys.exit(1)

    # Step 7: Report success
    improvement = verify_report.balanced_accuracy - baseline_report.balanced_accuracy
    print(f"\nImprovement accepted!")
    print(f"  Baseline accuracy:      {baseline_report.balanced_accuracy:.3f}")
    print(f"  Verification accuracy:  {verify_report.balanced_accuracy:.3f}")
    print(f"  Improvement:            {improvement:+.3f}")

    # Git commit
    if not args.no_commit:
        try:
            subprocess.run(
                ["git", "add", str(reviewer_path)],
                check=True,
                capture_output=True,
            )
            subprocess.run(
                [
                    "git", "commit", "-m",
                    f"improve: update reviewer learned patterns (accuracy {baseline_report.balanced_accuracy:.3f} -> {verify_report.balanced_accuracy:.3f})",
                ],
                check=True,
                capture_output=True,
            )
            print("Changes committed to git.")
        except (subprocess.CalledProcessError, FileNotFoundError) as e:
            print(f"WARNING: Git commit failed: {e}", file=sys.stderr)


def _run_benchmark(
    samples: list,
    reviewer_instructions: str,
    *,
    model: str,
    trials: int,
    api_key: str,
) -> list:
    """Run a benchmark against all samples.

    Args:
        samples: List of BenchmarkSample
        reviewer_instructions: Reviewer prompt text
        model: Model identifier
        trials: Number of trials per sample
        api_key: Anthropic API key

    Returns:
        List of BenchmarkResult
    """
    import time
    from reviewer_benchmark import BenchmarkResult, build_reviewer_prompt, parse_verdict

    try:
        from anthropic import Anthropic
    except ImportError:
        print("ERROR: anthropic package not installed.", file=sys.stderr)
        sys.exit(1)

    client = Anthropic(api_key=api_key)
    results: list = []
    total_calls = len(samples) * trials
    call_num = 0

    for sample in samples:
        for trial in range(trials):
            call_num += 1
            print(
                f"  [{call_num}/{total_calls}] {sample.sample_id} trial {trial + 1}...",
                end=" ",
                flush=True,
            )

            prompt = build_reviewer_prompt(sample, reviewer_instructions)
            try:
                message = client.messages.create(
                    model=model,
                    max_tokens=4096,
                    messages=[{"role": "user", "content": prompt}],
                )
                response = message.content[0].text
            except Exception as e:
                print(f"API error: {e}")
                response = ""

            verdict, findings = parse_verdict(response)
            results.append(
                BenchmarkResult(
                    sample_id=sample.sample_id,
                    predicted_verdict=verdict,
                    expected_verdict=sample.expected_verdict,
                    findings=findings,
                    raw_response=response,
                    trial_index=trial,
                )
            )

            status = "OK" if verdict != "PARSE_ERROR" else "PARSE_ERROR"
            print(f"{verdict} [{status}]")

            if call_num < total_calls:
                time.sleep(0.5)

    return results


if __name__ == "__main__":
    main()
