"""Acceptance tests for: Issues #611, #612, #613, #614 — Pipeline Performance Optimizations

Generated by acceptance-first pipeline mode.
Validates 5 optimizations: reviewer static-only review, auto-detect --light for file paths,
research skip for fully-specified changes, and parallel STEP 10 validation.
"""

import re
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]

REVIEWER_PATH = PROJECT_ROOT / "plugins/autonomous-dev/agents/reviewer.md"
IMPLEMENT_PATH = PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md"


class TestAcceptancePipelinePerf:
    """Acceptance criteria from Issues #611, #612, #613, #614."""

    # AC1: Reviewer does NOT execute pytest (#611)
    def test_reviewer_does_not_run_pytest(self):
        """Reviewer agent must not contain instructions to execute pytest."""
        content = REVIEWER_PATH.read_text()
        lines = content.split("\n")
        for i, line in enumerate(lines):
            lower = line.lower().strip()
            if "must not" in lower or "forbidden" in lower or "do not" in lower:
                continue
            if "run" in lower and "pytest" in lower and "must not" not in lower:
                if "re-run" not in lower and "not re-run" not in lower:
                    pytest.fail(
                        f"reviewer.md line {i+1} appears to instruct running pytest: "
                        f"'{line.strip()}'. Reviewer should do static review only (#611)."
                    )

    def test_reviewer_requires_test_artifact(self):
        """Reviewer must require STEP 8 test results as context input."""
        content = REVIEWER_PATH.read_text()
        assert "test artifact" in content.lower() or "test results" in content.lower(), (
            "reviewer.md must reference 'test artifact' or 'test results' — "
            "reviewer should consume STEP 8 results as context, not re-run tests (#611)."
        )

    def test_reviewer_blocks_without_test_results(self):
        """Reviewer must block (REQUEST_CHANGES) if no test results provided."""
        content = REVIEWER_PATH.read_text()
        assert "missing test" in content.lower() or "no test artifact" in content.lower() or "without test results" in content.lower(), (
            "reviewer.md must specify behavior when test results are missing — "
            "should issue REQUEST_CHANGES, not silently approve (#611)."
        )

    def test_reviewer_forbidden_re_run_pytest(self):
        """Reviewer must explicitly FORBID re-running pytest."""
        content = REVIEWER_PATH.read_text()
        assert re.search(
            r"(must not|forbidden|do not).{0,60}(re-run|run|execute).{0,30}pytest",
            content.lower(),
        ), (
            "reviewer.md must explicitly forbid re-running pytest. "
            "The reviewer is read-only and should not execute tests (#611)."
        )

    # AC2: implement.md passes test results to reviewer (#611)
    def test_implement_passes_test_results_to_reviewer(self):
        """implement.md STEP 10a must pass STEP 8 test results to reviewer."""
        content = IMPLEMENT_PATH.read_text()
        step10_match = re.search(r"STEP 10[a-z]*:.*Reviewer", content, re.IGNORECASE)
        assert step10_match, "implement.md must have a STEP 10a for Reviewer"
        step10_section = content[step10_match.start() : step10_match.start() + 3000]
        assert "test result" in step10_section.lower() or "step 8" in step10_section.lower(), (
            "implement.md STEP 10a must reference passing STEP 8 test results to reviewer (#611)."
        )

    # AC3: Auto-detect --light for file paths (#612)
    def test_implement_file_path_light_detection(self):
        """implement.md STEP 0 must detect file paths for --light suggestion."""
        content = IMPLEMENT_PATH.read_text()
        step0_match = re.search(r"STEP 0.*Parse", content)
        assert step0_match, "implement.md must have STEP 0"
        step1_match = re.search(r"### STEP 1:", content)
        step0_end = step1_match.start() if step1_match else step0_match.start() + 5000
        step0_section = content[step0_match.start() : step0_end]
        assert "file path" in step0_section.lower() or "file-path" in step0_section.lower(), (
            "implement.md STEP 0 must include file-path-based --light detection (#612)."
        )

    def test_implement_security_exclusion_for_light(self):
        """implement.md must exclude security-sensitive files from --light auto-detect."""
        content = IMPLEMENT_PATH.read_text()
        assert ".py" in content and "security" in content.lower()

    # AC4: Research skip for fully-specified changes (#613)
    def test_implement_fully_specified_skip(self):
        """implement.md must support skipping research for fully-specified changes."""
        content = IMPLEMENT_PATH.read_text()
        assert "fully-specified" in content.lower() or "fully specified" in content.lower(), (
            "implement.md must include 'fully-specified change' detection logic (#613)."
        )

    def test_implement_research_skip_safeguards(self):
        """Research skip must have safeguards (security topics, multi-file changes)."""
        content = IMPLEMENT_PATH.read_text()
        fs_match = re.search(r"fully.specified", content, re.IGNORECASE)
        if not fs_match:
            pytest.skip("fully-specified detection not yet implemented")
        fs_section = content[fs_match.start() : fs_match.start() + 2000]
        assert "security" in fs_section.lower() or "authentication" in fs_section.lower(), (
            "Research skip must safeguard against skipping for security-related changes (#613)."
        )

    # AC5: Parallel STEP 10 validation (#614)
    def test_implement_parallel_validation_option(self):
        """implement.md STEP 10 must support parallel validation for low-risk changes."""
        content = IMPLEMENT_PATH.read_text()
        step10_match = re.search(r"### STEP 10:", content)
        assert step10_match, "implement.md must have STEP 10"
        step10_section = content[step10_match.start() : step10_match.start() + 5000]
        assert "parallel" in step10_section.lower(), (
            "implement.md STEP 10 must mention parallel execution option (#614)."
        )

    def test_implement_sequential_preserved_for_security(self):
        """implement.md must preserve sequential STEP 10 for security-sensitive changes."""
        content = IMPLEMENT_PATH.read_text()
        step10_match = re.search(r"### STEP 10:", content)
        assert step10_match, "implement.md must have STEP 10"
        step10_section = content[step10_match.start() : step10_match.start() + 5000]
        assert "sequential" in step10_section.lower(), (
            "implement.md STEP 10 must preserve sequential mode (#614)."
        )

    def test_implement_security_sensitive_patterns_defined(self):
        """implement.md must define security-sensitive file patterns for STEP 10 routing."""
        content = IMPLEMENT_PATH.read_text()
        step10_match = re.search(r"### STEP 10:", content)
        assert step10_match, "implement.md must have STEP 10"
        step10_section = content[step10_match.start() : step10_match.start() + 5000]
        assert "hooks/" in step10_section or "*.py" in step10_section, (
            "implement.md STEP 10 must define security-sensitive file patterns (#614)."
        )
